const mongoose = require("mongoose");

// Coupon — discount codes the admin creates for customers to redeem.
// Surfaced on the home-page promo banner and (eventually) during checkout.
//
// Lifecycle:
//   admin creates → status "active"
//   admin pauses manually → status "paused"
//   expiresAt passes OR currentUses hits maxUses → virtually "expired"
//
// The `status` field only stores admin-controlled states (active/paused).
// Expiry is derived at read time from expiresAt + currentUses so we don't
// need a cron job to flip the flag — the derived helper is in the controller.
const couponSchema = new mongoose.Schema(
  {
    // Promo code the user types at checkout. Stored uppercase + trimmed so
    // "sana3a30" and "SANA3A30" match.
    code: {
      type: String,
      required: [true, "Code is required"],
      uppercase: true,
      trim: true,
      unique: true,
      index: true,
    },

    // Short human label shown under the code in the admin table (e.g.
    // "عقد صيانة دورية").
    description: { type: String, default: "" },

    // "percentage" → discountValue is a percent (0-100).
    // "fixed"      → discountValue is an absolute amount in ج.م.
    discountType: {
      type: String,
      enum: ["percentage", "fixed"],
      default: "percentage",
    },
    discountValue: { type: Number, required: true, min: 0 },

    // Which categories the coupon applies to. Empty array means "all services".
    // Storing IDs keeps things normalized; the controller resolves names when
    // returning to the admin UI.
    applicableCategories: [{
      type: mongoose.Schema.Types.ObjectId,
      ref: "Category",
    }],

    // Minimum order total required for the coupon to apply. 0 = no minimum.
    minOrderAmount: { type: Number, default: 0 },

    // Usage cap. Null/0 = unlimited (the UI shows "∞").
    maxUses: { type: Number, default: 0 },
    currentUses: { type: Number, default: 0 },

    // Total revenue generated by orders that used this coupon. Incremented
    // on redemption by the checkout flow (hook to be added later).
    revenueGenerated: { type: Number, default: 0 },

    // When the coupon stops being valid. Past this date the coupon is
    // considered "expired" regardless of status.
    expiresAt: { type: Date, required: true },

    // Admin-controlled flag. Separate from expiry so an admin can pause
    // a still-in-date coupon without deleting it.
    status: {
      type: String,
      enum: ["active", "paused"],
      default: "active",
    },

    // Home-page banner content — lets the admin use a single coupon entry
    // to drive the home page promotion block without duplicating data.
    // If showOnHomePage is true, the public /api/coupons/featured endpoint
    // will return this coupon (most-recent wins if multiple are flagged).
    showOnHomePage: { type: Boolean, default: false },
    bannerImage: { type: String, default: "" },        // URL
    bannerTitle: { type: String, default: "" },        // e.g. "وفر ٣٠٪ على أول خدمة تنظيف لك"
    bannerSubtitle: { type: String, default: "" },     // Optional secondary line
    bannerCtaLabel: { type: String, default: "استفد من العرض" },
  },
  { timestamps: true },
);

module.exports = mongoose.model("Coupon", couponSchema);
